#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRCodeBasedLMS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbLibraryManagement")]
	public partial class dcLMSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblAttendance(tblAttendance instance);
    partial void UpdatetblAttendance(tblAttendance instance);
    partial void DeletetblAttendance(tblAttendance instance);
    partial void InserttblUserAccount(tblUserAccount instance);
    partial void UpdatetblUserAccount(tblUserAccount instance);
    partial void DeletetblUserAccount(tblUserAccount instance);
    partial void InserttblBook(tblBook instance);
    partial void UpdatetblBook(tblBook instance);
    partial void DeletetblBook(tblBook instance);
    partial void InserttblBookCopy(tblBookCopy instance);
    partial void UpdatetblBookCopy(tblBookCopy instance);
    partial void DeletetblBookCopy(tblBookCopy instance);
    partial void InserttblBorrow(tblBorrow instance);
    partial void UpdatetblBorrow(tblBorrow instance);
    partial void DeletetblBorrow(tblBorrow instance);
    partial void InserttblLibraryUser(tblLibraryUser instance);
    partial void UpdatetblLibraryUser(tblLibraryUser instance);
    partial void DeletetblLibraryUser(tblLibraryUser instance);
    partial void InserttblSelectedBook(tblSelectedBook instance);
    partial void UpdatetblSelectedBook(tblSelectedBook instance);
    partial void DeletetblSelectedBook(tblSelectedBook instance);
    #endregion
		
		public dcLMSDataContext() : 
				base(global::QRCodeBasedLMS.Properties.Settings.Default.dbLibraryManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dcLMSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcLMSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcLMSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcLMSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblAttendance> tblAttendances
		{
			get
			{
				return this.GetTable<tblAttendance>();
			}
		}
		
		public System.Data.Linq.Table<tblUserAccount> tblUserAccounts
		{
			get
			{
				return this.GetTable<tblUserAccount>();
			}
		}
		
		public System.Data.Linq.Table<tblBook> tblBooks
		{
			get
			{
				return this.GetTable<tblBook>();
			}
		}
		
		public System.Data.Linq.Table<tblBookCopy> tblBookCopies
		{
			get
			{
				return this.GetTable<tblBookCopy>();
			}
		}
		
		public System.Data.Linq.Table<tblBorrow> tblBorrows
		{
			get
			{
				return this.GetTable<tblBorrow>();
			}
		}
		
		public System.Data.Linq.Table<tblLibraryUser> tblLibraryUsers
		{
			get
			{
				return this.GetTable<tblLibraryUser>();
			}
		}
		
		public System.Data.Linq.Table<tblSelectedBook> tblSelectedBooks
		{
			get
			{
				return this.GetTable<tblSelectedBook>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_AccountIDnumber")]
		public int sp_AccountIDnumber()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_AddAccount", IsComposable=true)]
		public object sp_AddAccount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserNum", DbType="VarChar(50)")] string userNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Firstname", DbType="VarChar(100)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lastname", DbType="VarChar(100)")] string lastname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="VarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SecretQuestion", DbType="VarChar(100)")] string secretQuestion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SecretAnswer", DbType="VarChar(100)")] string secretAnswer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserType", DbType="VarChar(20)")] string userType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(10)")] string status)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userNum, firstname, lastname, username, password, secretQuestion, secretAnswer, userType, status).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_AddBook")]
		public int sp_AddBook([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BookNum", DbType="VarChar(50)")] string bookNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BookType", DbType="VarChar(50)")] string bookType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISBN", DbType="VarChar(50)")] string iSBN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccNum", DbType="Int")] System.Nullable<int> accNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CallNum", DbType="VarChar(50)")] string callNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateReceived", DbType="Date")] System.Nullable<System.DateTime> dateReceived, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="VarChar(200)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Author", DbType="VarChar(50)")] string author, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Publisher", DbType="VarChar(100)")] string publisher, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CopyrightYear", DbType="Int")] System.Nullable<int> copyrightYear, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Edition", DbType="VarChar(50)")] string edition, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Volume", DbType="VarChar(50)")] string volume, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pages", DbType="Int")] System.Nullable<int> pages, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(20)")] string status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Remarks", DbType="VarChar(200)")] string remarks)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bookNum, bookType, iSBN, accNum, callNum, dateReceived, title, author, publisher, copyrightYear, edition, volume, pages, status, remarks);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_AddBookCopy")]
		public int sp_AddBookCopy([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BookNum", DbType="VarChar(50)")] string bookNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccNum", DbType="Int")] System.Nullable<int> accNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateReceived", DbType="Date")] System.Nullable<System.DateTime> dateReceived, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(20)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bookNum, accNum, dateReceived, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_AddBorrower", IsComposable=true)]
		public object sp_AddBorrower([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BorrowerNum", DbType="VarChar(50)")] string borrowerNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SchoolID", DbType="VarChar(20)")] string schoolID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Firstname", DbType="VarChar(100)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lastname", DbType="VarChar(100)")] string lastname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section", DbType="VarChar(50)")] string section, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="VarChar(10)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="VarChar(100)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactNumber", DbType="VarChar(50)")] string contactNumber)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), borrowerNum, schoolID, firstname, lastname, section, gender, address, contactNumber).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_AddLibraryUser")]
		public int sp_AddLibraryUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SchoolID", DbType="VarChar(50)")] string schoolID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Firstname", DbType="VarChar(100)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lastname", DbType="VarChar(100)")] string lastname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="VarChar(10)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="VarChar(100)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactNumber", DbType="VarChar(50)")] string contactNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserType", DbType="VarChar(50)")] string userType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SchoolYear", DbType="VarChar(50)")] string schoolYear, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="WithLibraryCard", DbType="Bit")] System.Nullable<bool> withLibraryCard)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), schoolID, firstname, lastname, gender, address, contactNumber, userType, schoolYear, withLibraryCard);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Attendance")]
		public int sp_Attendance([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StudentID", DbType="VarChar(50)")] string studentID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LoginTime", DbType="DateTime")] System.Nullable<System.DateTime> loginTime)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), studentID, name, loginTime);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BookIDnumber")]
		public int sp_BookIDnumber()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BorrowIDnumber")]
		public int sp_BorrowIDnumber()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SearchActiveAccount", IsComposable=true)]
		public object sp_SearchActiveAccount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="VarChar(50)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string searchkey)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), category, searchkey).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SearchBook")]
		public ISingleResult<sp_SearchBookResult> sp_SearchBook([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="VarChar(50)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string searchKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), category, searchKey);
			return ((ISingleResult<sp_SearchBookResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SearchBorrower", IsComposable=true)]
		public object sp_SearchBorrower([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="VarChar(50)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string searchkey)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), category, searchkey).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SearchInactiveAccount", IsComposable=true)]
		public object sp_SearchInactiveAccount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="VarChar(50)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string searchkey)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), category, searchkey).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TotalBookCopy")]
		public ISingleResult<sp_TotalBookCopyResult> sp_TotalBookCopy([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BookNum", DbType="VarChar(50)")] string bookNum)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bookNum);
			return ((ISingleResult<sp_TotalBookCopyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateAccount", IsComposable=true)]
		public object sp_UpdateAccount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserNum", DbType="VarChar(50)")] string userNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Firstname", DbType="VarChar(100)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lastname", DbType="VarChar(100)")] string lastname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="VarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SecretQuestion", DbType="VarChar(100)")] string secretQuestion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SecretAnswer", DbType="VarChar(100)")] string secretAnswer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserType", DbType="VarChar(20)")] string userType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(10)")] string status)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userNum, firstname, lastname, username, password, secretQuestion, secretAnswer, userType, status).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateAccountStatus", IsComposable=true)]
		public object sp_UpdateAccountStatus([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserNum", DbType="VarChar(50)")] string userNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(10)")] string status)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userNum, status).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateBook")]
		public int sp_UpdateBook([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BookNum", DbType="VarChar(50)")] string bookNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BookType", DbType="VarChar(50)")] string bookType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISBN", DbType="VarChar(50)")] string iSBN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CallNum", DbType="VarChar(50)")] string callNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="VarChar(200)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Author", DbType="VarChar(50)")] string author, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Publisher", DbType="VarChar(100)")] string publisher, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CopyrightYear", DbType="Int")] System.Nullable<int> copyrightYear, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Edition", DbType="VarChar(50)")] string edition, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Volume", DbType="VarChar(50)")] string volume, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pages", DbType="Int")] System.Nullable<int> pages, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Remarks", DbType="VarChar(200)")] string remarks)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bookNum, bookType, iSBN, callNum, title, author, publisher, copyrightYear, edition, volume, pages, remarks);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateBorrower", IsComposable=true)]
		public object sp_UpdateBorrower([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BorrowerNum", DbType="VarChar(50)")] string borrowerNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SchoolID", DbType="VarChar(20)")] string schoolID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Firstname", DbType="VarChar(100)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lastname", DbType="VarChar(100)")] string lastname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section", DbType="VarChar(50)")] string section, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="VarChar(10)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="VarChar(100)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactNumber", DbType="VarChar(50)")] string contactNumber)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), borrowerNum, schoolID, firstname, lastname, section, gender, address, contactNumber).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateLibraryUser")]
		public int sp_UpdateLibraryUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SchoolID", DbType="VarChar(50)")] string schoolID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Firstname", DbType="VarChar(100)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lastname", DbType="VarChar(100)")] string lastname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="VarChar(10)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="VarChar(100)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactNumber", DbType="VarChar(50)")] string contactNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SchoolYear", DbType="VarChar(50)")] string schoolYear, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="WithLibraryCard", DbType="Bit")] System.Nullable<bool> withLibraryCard)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), schoolID, firstname, lastname, gender, address, contactNumber, schoolYear, withLibraryCard);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ViewActiveAccount", IsComposable=true)]
		public object sp_ViewActiveAccount()
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ViewBook")]
		public ISingleResult<sp_ViewBookResult> sp_ViewBook()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_ViewBookResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ViewBookCopy")]
		public ISingleResult<sp_ViewBookCopyResult> sp_ViewBookCopy([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BookNum", DbType="VarChar(50)")] string bookNum)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bookNum);
			return ((ISingleResult<sp_ViewBookCopyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ViewBorrower", IsComposable=true)]
		public object sp_ViewBorrower()
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ViewInactiveAccount", IsComposable=true)]
		public object sp_ViewInactiveAccount()
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ViewLibraryUser")]
		public ISingleResult<sp_ViewLibraryUserResult> sp_ViewLibraryUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SchoolYear", DbType="VarChar(50)")] string schoolYear)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), schoolYear);
			return ((ISingleResult<sp_ViewLibraryUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_DeleteSelectedBooks")]
		public int sp_DeleteSelectedBooks([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BookIDNum", DbType="VarChar(50)")] string bookIDNum)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bookIDNum);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ViewSelectedBooks")]
		public ISingleResult<sp_ViewSelectedBooksResult> sp_ViewSelectedBooks()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_ViewSelectedBooksResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BorrowBook")]
		public int sp_BorrowBook([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BorrowNum", DbType="VarChar(50)")] string borrowNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SchoolID", DbType="VarChar(50)")] string schoolID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BookNum", DbType="VarChar(50)")] string bookNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BorrowedDate", DbType="DateTime")] System.Nullable<System.DateTime> borrowedDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DueDate", DbType="Date")] System.Nullable<System.DateTime> dueDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), borrowNum, schoolID, bookNum, borrowedDate, dueDate);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SelectBooks")]
		public int sp_SelectBooks([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BookNum", DbType="VarChar(50)")] string bookNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="VarChar(100)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DueDate", DbType="Date")] System.Nullable<System.DateTime> dueDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bookNum, title, dueDate);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAttendance")]
	public partial class tblAttendance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _attendance_AttendanceID;
		
		private string _attendance_StudentIDNum;
		
		private string _attendance_Name;
		
		private System.Nullable<System.DateTime> _attendance_LoginTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onattendance_AttendanceIDChanging(int value);
    partial void Onattendance_AttendanceIDChanged();
    partial void Onattendance_StudentIDNumChanging(string value);
    partial void Onattendance_StudentIDNumChanged();
    partial void Onattendance_NameChanging(string value);
    partial void Onattendance_NameChanged();
    partial void Onattendance_LoginTimeChanging(System.Nullable<System.DateTime> value);
    partial void Onattendance_LoginTimeChanged();
    #endregion
		
		public tblAttendance()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attendance_AttendanceID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int attendance_AttendanceID
		{
			get
			{
				return this._attendance_AttendanceID;
			}
			set
			{
				if ((this._attendance_AttendanceID != value))
				{
					this.Onattendance_AttendanceIDChanging(value);
					this.SendPropertyChanging();
					this._attendance_AttendanceID = value;
					this.SendPropertyChanged("attendance_AttendanceID");
					this.Onattendance_AttendanceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attendance_StudentIDNum", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string attendance_StudentIDNum
		{
			get
			{
				return this._attendance_StudentIDNum;
			}
			set
			{
				if ((this._attendance_StudentIDNum != value))
				{
					this.Onattendance_StudentIDNumChanging(value);
					this.SendPropertyChanging();
					this._attendance_StudentIDNum = value;
					this.SendPropertyChanged("attendance_StudentIDNum");
					this.Onattendance_StudentIDNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attendance_Name", DbType="VarChar(50)")]
		public string attendance_Name
		{
			get
			{
				return this._attendance_Name;
			}
			set
			{
				if ((this._attendance_Name != value))
				{
					this.Onattendance_NameChanging(value);
					this.SendPropertyChanging();
					this._attendance_Name = value;
					this.SendPropertyChanged("attendance_Name");
					this.Onattendance_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attendance_LoginTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> attendance_LoginTime
		{
			get
			{
				return this._attendance_LoginTime;
			}
			set
			{
				if ((this._attendance_LoginTime != value))
				{
					this.Onattendance_LoginTimeChanging(value);
					this.SendPropertyChanging();
					this._attendance_LoginTime = value;
					this.SendPropertyChanged("attendance_LoginTime");
					this.Onattendance_LoginTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUserAccount")]
	public partial class tblUserAccount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_UserID;
		
		private string _user_UserNum;
		
		private string _user_Firstname;
		
		private string _user_Lastname;
		
		private string _user_Username;
		
		private string _user_Password;
		
		private string _user_SecretQuestion;
		
		private string _user_SecretAnswer;
		
		private string _user_UserType;
		
		private string _user_Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_UserIDChanging(int value);
    partial void Onuser_UserIDChanged();
    partial void Onuser_UserNumChanging(string value);
    partial void Onuser_UserNumChanged();
    partial void Onuser_FirstnameChanging(string value);
    partial void Onuser_FirstnameChanged();
    partial void Onuser_LastnameChanging(string value);
    partial void Onuser_LastnameChanged();
    partial void Onuser_UsernameChanging(string value);
    partial void Onuser_UsernameChanged();
    partial void Onuser_PasswordChanging(string value);
    partial void Onuser_PasswordChanged();
    partial void Onuser_SecretQuestionChanging(string value);
    partial void Onuser_SecretQuestionChanged();
    partial void Onuser_SecretAnswerChanging(string value);
    partial void Onuser_SecretAnswerChanged();
    partial void Onuser_UserTypeChanging(string value);
    partial void Onuser_UserTypeChanged();
    partial void Onuser_StatusChanging(string value);
    partial void Onuser_StatusChanged();
    #endregion
		
		public tblUserAccount()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_UserID
		{
			get
			{
				return this._user_UserID;
			}
			set
			{
				if ((this._user_UserID != value))
				{
					this.Onuser_UserIDChanging(value);
					this.SendPropertyChanging();
					this._user_UserID = value;
					this.SendPropertyChanged("user_UserID");
					this.Onuser_UserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_UserNum", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string user_UserNum
		{
			get
			{
				return this._user_UserNum;
			}
			set
			{
				if ((this._user_UserNum != value))
				{
					this.Onuser_UserNumChanging(value);
					this.SendPropertyChanging();
					this._user_UserNum = value;
					this.SendPropertyChanged("user_UserNum");
					this.Onuser_UserNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_Firstname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string user_Firstname
		{
			get
			{
				return this._user_Firstname;
			}
			set
			{
				if ((this._user_Firstname != value))
				{
					this.Onuser_FirstnameChanging(value);
					this.SendPropertyChanging();
					this._user_Firstname = value;
					this.SendPropertyChanged("user_Firstname");
					this.Onuser_FirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_Lastname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string user_Lastname
		{
			get
			{
				return this._user_Lastname;
			}
			set
			{
				if ((this._user_Lastname != value))
				{
					this.Onuser_LastnameChanging(value);
					this.SendPropertyChanging();
					this._user_Lastname = value;
					this.SendPropertyChanged("user_Lastname");
					this.Onuser_LastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string user_Username
		{
			get
			{
				return this._user_Username;
			}
			set
			{
				if ((this._user_Username != value))
				{
					this.Onuser_UsernameChanging(value);
					this.SendPropertyChanging();
					this._user_Username = value;
					this.SendPropertyChanged("user_Username");
					this.Onuser_UsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string user_Password
		{
			get
			{
				return this._user_Password;
			}
			set
			{
				if ((this._user_Password != value))
				{
					this.Onuser_PasswordChanging(value);
					this.SendPropertyChanging();
					this._user_Password = value;
					this.SendPropertyChanged("user_Password");
					this.Onuser_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_SecretQuestion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string user_SecretQuestion
		{
			get
			{
				return this._user_SecretQuestion;
			}
			set
			{
				if ((this._user_SecretQuestion != value))
				{
					this.Onuser_SecretQuestionChanging(value);
					this.SendPropertyChanging();
					this._user_SecretQuestion = value;
					this.SendPropertyChanged("user_SecretQuestion");
					this.Onuser_SecretQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_SecretAnswer", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string user_SecretAnswer
		{
			get
			{
				return this._user_SecretAnswer;
			}
			set
			{
				if ((this._user_SecretAnswer != value))
				{
					this.Onuser_SecretAnswerChanging(value);
					this.SendPropertyChanging();
					this._user_SecretAnswer = value;
					this.SendPropertyChanged("user_SecretAnswer");
					this.Onuser_SecretAnswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_UserType", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string user_UserType
		{
			get
			{
				return this._user_UserType;
			}
			set
			{
				if ((this._user_UserType != value))
				{
					this.Onuser_UserTypeChanging(value);
					this.SendPropertyChanging();
					this._user_UserType = value;
					this.SendPropertyChanged("user_UserType");
					this.Onuser_UserTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_Status", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string user_Status
		{
			get
			{
				return this._user_Status;
			}
			set
			{
				if ((this._user_Status != value))
				{
					this.Onuser_StatusChanging(value);
					this.SendPropertyChanging();
					this._user_Status = value;
					this.SendPropertyChanged("user_Status");
					this.Onuser_StatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBook")]
	public partial class tblBook : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _book_BookID;
		
		private string _book_BookNum;
		
		private string _book_BookType;
		
		private string _book_ISBN;
		
		private string _book_CallNum;
		
		private string _book_Title;
		
		private string _book_Author;
		
		private string _book_Publisher;
		
		private int _book_CopyrightYear;
		
		private string _book_Edition;
		
		private string _book_Volume;
		
		private System.Nullable<int> _book_Pages;
		
		private string _book_Remarks;
		
		private EntitySet<tblBookCopy> _tblBookCopies;
		
		private EntitySet<tblBorrow> _tblBorrows;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbook_BookIDChanging(int value);
    partial void Onbook_BookIDChanged();
    partial void Onbook_BookNumChanging(string value);
    partial void Onbook_BookNumChanged();
    partial void Onbook_BookTypeChanging(string value);
    partial void Onbook_BookTypeChanged();
    partial void Onbook_ISBNChanging(string value);
    partial void Onbook_ISBNChanged();
    partial void Onbook_CallNumChanging(string value);
    partial void Onbook_CallNumChanged();
    partial void Onbook_TitleChanging(string value);
    partial void Onbook_TitleChanged();
    partial void Onbook_AuthorChanging(string value);
    partial void Onbook_AuthorChanged();
    partial void Onbook_PublisherChanging(string value);
    partial void Onbook_PublisherChanged();
    partial void Onbook_CopyrightYearChanging(int value);
    partial void Onbook_CopyrightYearChanged();
    partial void Onbook_EditionChanging(string value);
    partial void Onbook_EditionChanged();
    partial void Onbook_VolumeChanging(string value);
    partial void Onbook_VolumeChanged();
    partial void Onbook_PagesChanging(System.Nullable<int> value);
    partial void Onbook_PagesChanged();
    partial void Onbook_RemarksChanging(string value);
    partial void Onbook_RemarksChanged();
    #endregion
		
		public tblBook()
		{
			this._tblBookCopies = new EntitySet<tblBookCopy>(new Action<tblBookCopy>(this.attach_tblBookCopies), new Action<tblBookCopy>(this.detach_tblBookCopies));
			this._tblBorrows = new EntitySet<tblBorrow>(new Action<tblBorrow>(this.attach_tblBorrows), new Action<tblBorrow>(this.detach_tblBorrows));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_BookID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int book_BookID
		{
			get
			{
				return this._book_BookID;
			}
			set
			{
				if ((this._book_BookID != value))
				{
					this.Onbook_BookIDChanging(value);
					this.SendPropertyChanging();
					this._book_BookID = value;
					this.SendPropertyChanged("book_BookID");
					this.Onbook_BookIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_BookNum", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string book_BookNum
		{
			get
			{
				return this._book_BookNum;
			}
			set
			{
				if ((this._book_BookNum != value))
				{
					this.Onbook_BookNumChanging(value);
					this.SendPropertyChanging();
					this._book_BookNum = value;
					this.SendPropertyChanged("book_BookNum");
					this.Onbook_BookNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_BookType", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string book_BookType
		{
			get
			{
				return this._book_BookType;
			}
			set
			{
				if ((this._book_BookType != value))
				{
					this.Onbook_BookTypeChanging(value);
					this.SendPropertyChanging();
					this._book_BookType = value;
					this.SendPropertyChanged("book_BookType");
					this.Onbook_BookTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_ISBN", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string book_ISBN
		{
			get
			{
				return this._book_ISBN;
			}
			set
			{
				if ((this._book_ISBN != value))
				{
					this.Onbook_ISBNChanging(value);
					this.SendPropertyChanging();
					this._book_ISBN = value;
					this.SendPropertyChanged("book_ISBN");
					this.Onbook_ISBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_CallNum", DbType="VarChar(50)")]
		public string book_CallNum
		{
			get
			{
				return this._book_CallNum;
			}
			set
			{
				if ((this._book_CallNum != value))
				{
					this.Onbook_CallNumChanging(value);
					this.SendPropertyChanging();
					this._book_CallNum = value;
					this.SendPropertyChanged("book_CallNum");
					this.Onbook_CallNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_Title", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string book_Title
		{
			get
			{
				return this._book_Title;
			}
			set
			{
				if ((this._book_Title != value))
				{
					this.Onbook_TitleChanging(value);
					this.SendPropertyChanging();
					this._book_Title = value;
					this.SendPropertyChanged("book_Title");
					this.Onbook_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_Author", DbType="VarChar(50)")]
		public string book_Author
		{
			get
			{
				return this._book_Author;
			}
			set
			{
				if ((this._book_Author != value))
				{
					this.Onbook_AuthorChanging(value);
					this.SendPropertyChanging();
					this._book_Author = value;
					this.SendPropertyChanged("book_Author");
					this.Onbook_AuthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_Publisher", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string book_Publisher
		{
			get
			{
				return this._book_Publisher;
			}
			set
			{
				if ((this._book_Publisher != value))
				{
					this.Onbook_PublisherChanging(value);
					this.SendPropertyChanging();
					this._book_Publisher = value;
					this.SendPropertyChanged("book_Publisher");
					this.Onbook_PublisherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_CopyrightYear", DbType="Int NOT NULL")]
		public int book_CopyrightYear
		{
			get
			{
				return this._book_CopyrightYear;
			}
			set
			{
				if ((this._book_CopyrightYear != value))
				{
					this.Onbook_CopyrightYearChanging(value);
					this.SendPropertyChanging();
					this._book_CopyrightYear = value;
					this.SendPropertyChanged("book_CopyrightYear");
					this.Onbook_CopyrightYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_Edition", DbType="VarChar(50)")]
		public string book_Edition
		{
			get
			{
				return this._book_Edition;
			}
			set
			{
				if ((this._book_Edition != value))
				{
					this.Onbook_EditionChanging(value);
					this.SendPropertyChanging();
					this._book_Edition = value;
					this.SendPropertyChanged("book_Edition");
					this.Onbook_EditionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_Volume", DbType="VarChar(50)")]
		public string book_Volume
		{
			get
			{
				return this._book_Volume;
			}
			set
			{
				if ((this._book_Volume != value))
				{
					this.Onbook_VolumeChanging(value);
					this.SendPropertyChanging();
					this._book_Volume = value;
					this.SendPropertyChanged("book_Volume");
					this.Onbook_VolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_Pages", DbType="Int")]
		public System.Nullable<int> book_Pages
		{
			get
			{
				return this._book_Pages;
			}
			set
			{
				if ((this._book_Pages != value))
				{
					this.Onbook_PagesChanging(value);
					this.SendPropertyChanging();
					this._book_Pages = value;
					this.SendPropertyChanged("book_Pages");
					this.Onbook_PagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_Remarks", DbType="VarChar(200)")]
		public string book_Remarks
		{
			get
			{
				return this._book_Remarks;
			}
			set
			{
				if ((this._book_Remarks != value))
				{
					this.Onbook_RemarksChanging(value);
					this.SendPropertyChanging();
					this._book_Remarks = value;
					this.SendPropertyChanged("book_Remarks");
					this.Onbook_RemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBook_tblBookCopy", Storage="_tblBookCopies", ThisKey="book_BookID", OtherKey="book_BookID")]
		public EntitySet<tblBookCopy> tblBookCopies
		{
			get
			{
				return this._tblBookCopies;
			}
			set
			{
				this._tblBookCopies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBook_tblBorrow", Storage="_tblBorrows", ThisKey="book_BookID", OtherKey="book_BookID")]
		public EntitySet<tblBorrow> tblBorrows
		{
			get
			{
				return this._tblBorrows;
			}
			set
			{
				this._tblBorrows.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblBookCopies(tblBookCopy entity)
		{
			this.SendPropertyChanging();
			entity.tblBook = this;
		}
		
		private void detach_tblBookCopies(tblBookCopy entity)
		{
			this.SendPropertyChanging();
			entity.tblBook = null;
		}
		
		private void attach_tblBorrows(tblBorrow entity)
		{
			this.SendPropertyChanging();
			entity.tblBook = this;
		}
		
		private void detach_tblBorrows(tblBorrow entity)
		{
			this.SendPropertyChanging();
			entity.tblBook = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBookCopy")]
	public partial class tblBookCopy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _copy_CopyID;
		
		private int _copy_AccNum;
		
		private System.Nullable<System.DateTime> _copy_DateReceived;
		
		private string _book_Status;
		
		private System.Nullable<int> _book_BookID;
		
		private EntityRef<tblBook> _tblBook;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncopy_CopyIDChanging(int value);
    partial void Oncopy_CopyIDChanged();
    partial void Oncopy_AccNumChanging(int value);
    partial void Oncopy_AccNumChanged();
    partial void Oncopy_DateReceivedChanging(System.Nullable<System.DateTime> value);
    partial void Oncopy_DateReceivedChanged();
    partial void Onbook_StatusChanging(string value);
    partial void Onbook_StatusChanged();
    partial void Onbook_BookIDChanging(System.Nullable<int> value);
    partial void Onbook_BookIDChanged();
    #endregion
		
		public tblBookCopy()
		{
			this._tblBook = default(EntityRef<tblBook>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_copy_CopyID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int copy_CopyID
		{
			get
			{
				return this._copy_CopyID;
			}
			set
			{
				if ((this._copy_CopyID != value))
				{
					this.Oncopy_CopyIDChanging(value);
					this.SendPropertyChanging();
					this._copy_CopyID = value;
					this.SendPropertyChanged("copy_CopyID");
					this.Oncopy_CopyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_copy_AccNum", DbType="Int NOT NULL")]
		public int copy_AccNum
		{
			get
			{
				return this._copy_AccNum;
			}
			set
			{
				if ((this._copy_AccNum != value))
				{
					this.Oncopy_AccNumChanging(value);
					this.SendPropertyChanging();
					this._copy_AccNum = value;
					this.SendPropertyChanged("copy_AccNum");
					this.Oncopy_AccNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_copy_DateReceived", DbType="Date")]
		public System.Nullable<System.DateTime> copy_DateReceived
		{
			get
			{
				return this._copy_DateReceived;
			}
			set
			{
				if ((this._copy_DateReceived != value))
				{
					this.Oncopy_DateReceivedChanging(value);
					this.SendPropertyChanging();
					this._copy_DateReceived = value;
					this.SendPropertyChanged("copy_DateReceived");
					this.Oncopy_DateReceivedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_Status", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string book_Status
		{
			get
			{
				return this._book_Status;
			}
			set
			{
				if ((this._book_Status != value))
				{
					this.Onbook_StatusChanging(value);
					this.SendPropertyChanging();
					this._book_Status = value;
					this.SendPropertyChanged("book_Status");
					this.Onbook_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_BookID", DbType="Int")]
		public System.Nullable<int> book_BookID
		{
			get
			{
				return this._book_BookID;
			}
			set
			{
				if ((this._book_BookID != value))
				{
					if (this._tblBook.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onbook_BookIDChanging(value);
					this.SendPropertyChanging();
					this._book_BookID = value;
					this.SendPropertyChanged("book_BookID");
					this.Onbook_BookIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBook_tblBookCopy", Storage="_tblBook", ThisKey="book_BookID", OtherKey="book_BookID", IsForeignKey=true)]
		public tblBook tblBook
		{
			get
			{
				return this._tblBook.Entity;
			}
			set
			{
				tblBook previousValue = this._tblBook.Entity;
				if (((previousValue != value) 
							|| (this._tblBook.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblBook.Entity = null;
						previousValue.tblBookCopies.Remove(this);
					}
					this._tblBook.Entity = value;
					if ((value != null))
					{
						value.tblBookCopies.Add(this);
						this._book_BookID = value.book_BookID;
					}
					else
					{
						this._book_BookID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblBook");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBorrow")]
	public partial class tblBorrow : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _borrow_BorrowID;
		
		private string _borrow_BorrowNum;
		
		private System.Nullable<int> _lib_UserID;
		
		private System.Nullable<int> _book_BookID;
		
		private System.DateTime _borrow_BorrowedDate;
		
		private System.DateTime _borrow_DueDate;
		
		private EntityRef<tblBook> _tblBook;
		
		private EntityRef<tblLibraryUser> _tblLibraryUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onborrow_BorrowIDChanging(int value);
    partial void Onborrow_BorrowIDChanged();
    partial void Onborrow_BorrowNumChanging(string value);
    partial void Onborrow_BorrowNumChanged();
    partial void Onlib_UserIDChanging(System.Nullable<int> value);
    partial void Onlib_UserIDChanged();
    partial void Onbook_BookIDChanging(System.Nullable<int> value);
    partial void Onbook_BookIDChanged();
    partial void Onborrow_BorrowedDateChanging(System.DateTime value);
    partial void Onborrow_BorrowedDateChanged();
    partial void Onborrow_DueDateChanging(System.DateTime value);
    partial void Onborrow_DueDateChanged();
    #endregion
		
		public tblBorrow()
		{
			this._tblBook = default(EntityRef<tblBook>);
			this._tblLibraryUser = default(EntityRef<tblLibraryUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_borrow_BorrowID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int borrow_BorrowID
		{
			get
			{
				return this._borrow_BorrowID;
			}
			set
			{
				if ((this._borrow_BorrowID != value))
				{
					this.Onborrow_BorrowIDChanging(value);
					this.SendPropertyChanging();
					this._borrow_BorrowID = value;
					this.SendPropertyChanged("borrow_BorrowID");
					this.Onborrow_BorrowIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_borrow_BorrowNum", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string borrow_BorrowNum
		{
			get
			{
				return this._borrow_BorrowNum;
			}
			set
			{
				if ((this._borrow_BorrowNum != value))
				{
					this.Onborrow_BorrowNumChanging(value);
					this.SendPropertyChanging();
					this._borrow_BorrowNum = value;
					this.SendPropertyChanged("borrow_BorrowNum");
					this.Onborrow_BorrowNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_UserID", DbType="Int")]
		public System.Nullable<int> lib_UserID
		{
			get
			{
				return this._lib_UserID;
			}
			set
			{
				if ((this._lib_UserID != value))
				{
					if (this._tblLibraryUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onlib_UserIDChanging(value);
					this.SendPropertyChanging();
					this._lib_UserID = value;
					this.SendPropertyChanged("lib_UserID");
					this.Onlib_UserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_BookID", DbType="Int")]
		public System.Nullable<int> book_BookID
		{
			get
			{
				return this._book_BookID;
			}
			set
			{
				if ((this._book_BookID != value))
				{
					if (this._tblBook.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onbook_BookIDChanging(value);
					this.SendPropertyChanging();
					this._book_BookID = value;
					this.SendPropertyChanged("book_BookID");
					this.Onbook_BookIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_borrow_BorrowedDate", DbType="Date NOT NULL")]
		public System.DateTime borrow_BorrowedDate
		{
			get
			{
				return this._borrow_BorrowedDate;
			}
			set
			{
				if ((this._borrow_BorrowedDate != value))
				{
					this.Onborrow_BorrowedDateChanging(value);
					this.SendPropertyChanging();
					this._borrow_BorrowedDate = value;
					this.SendPropertyChanged("borrow_BorrowedDate");
					this.Onborrow_BorrowedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_borrow_DueDate", DbType="Date NOT NULL")]
		public System.DateTime borrow_DueDate
		{
			get
			{
				return this._borrow_DueDate;
			}
			set
			{
				if ((this._borrow_DueDate != value))
				{
					this.Onborrow_DueDateChanging(value);
					this.SendPropertyChanging();
					this._borrow_DueDate = value;
					this.SendPropertyChanged("borrow_DueDate");
					this.Onborrow_DueDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBook_tblBorrow", Storage="_tblBook", ThisKey="book_BookID", OtherKey="book_BookID", IsForeignKey=true)]
		public tblBook tblBook
		{
			get
			{
				return this._tblBook.Entity;
			}
			set
			{
				tblBook previousValue = this._tblBook.Entity;
				if (((previousValue != value) 
							|| (this._tblBook.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblBook.Entity = null;
						previousValue.tblBorrows.Remove(this);
					}
					this._tblBook.Entity = value;
					if ((value != null))
					{
						value.tblBorrows.Add(this);
						this._book_BookID = value.book_BookID;
					}
					else
					{
						this._book_BookID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblBook");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLibraryUser_tblBorrow", Storage="_tblLibraryUser", ThisKey="lib_UserID", OtherKey="lib_UserID", IsForeignKey=true)]
		public tblLibraryUser tblLibraryUser
		{
			get
			{
				return this._tblLibraryUser.Entity;
			}
			set
			{
				tblLibraryUser previousValue = this._tblLibraryUser.Entity;
				if (((previousValue != value) 
							|| (this._tblLibraryUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblLibraryUser.Entity = null;
						previousValue.tblBorrows.Remove(this);
					}
					this._tblLibraryUser.Entity = value;
					if ((value != null))
					{
						value.tblBorrows.Add(this);
						this._lib_UserID = value.lib_UserID;
					}
					else
					{
						this._lib_UserID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblLibraryUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLibraryUser")]
	public partial class tblLibraryUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _lib_UserID;
		
		private string _lib_SchoolID;
		
		private string _lib_Firstname;
		
		private string _lib_Lastname;
		
		private string _lib_Gender;
		
		private string _lib_Address;
		
		private string _lib_ContactNumber;
		
		private string _lib_UserType;
		
		private string _lib_SchoolYear;
		
		private System.Nullable<bool> _lib_WithCard;
		
		private EntitySet<tblBorrow> _tblBorrows;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlib_UserIDChanging(int value);
    partial void Onlib_UserIDChanged();
    partial void Onlib_SchoolIDChanging(string value);
    partial void Onlib_SchoolIDChanged();
    partial void Onlib_FirstnameChanging(string value);
    partial void Onlib_FirstnameChanged();
    partial void Onlib_LastnameChanging(string value);
    partial void Onlib_LastnameChanged();
    partial void Onlib_GenderChanging(string value);
    partial void Onlib_GenderChanged();
    partial void Onlib_AddressChanging(string value);
    partial void Onlib_AddressChanged();
    partial void Onlib_ContactNumberChanging(string value);
    partial void Onlib_ContactNumberChanged();
    partial void Onlib_UserTypeChanging(string value);
    partial void Onlib_UserTypeChanged();
    partial void Onlib_SchoolYearChanging(string value);
    partial void Onlib_SchoolYearChanged();
    partial void Onlib_WithCardChanging(System.Nullable<bool> value);
    partial void Onlib_WithCardChanged();
    #endregion
		
		public tblLibraryUser()
		{
			this._tblBorrows = new EntitySet<tblBorrow>(new Action<tblBorrow>(this.attach_tblBorrows), new Action<tblBorrow>(this.detach_tblBorrows));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int lib_UserID
		{
			get
			{
				return this._lib_UserID;
			}
			set
			{
				if ((this._lib_UserID != value))
				{
					this.Onlib_UserIDChanging(value);
					this.SendPropertyChanging();
					this._lib_UserID = value;
					this.SendPropertyChanged("lib_UserID");
					this.Onlib_UserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_SchoolID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string lib_SchoolID
		{
			get
			{
				return this._lib_SchoolID;
			}
			set
			{
				if ((this._lib_SchoolID != value))
				{
					this.Onlib_SchoolIDChanging(value);
					this.SendPropertyChanging();
					this._lib_SchoolID = value;
					this.SendPropertyChanged("lib_SchoolID");
					this.Onlib_SchoolIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_Firstname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string lib_Firstname
		{
			get
			{
				return this._lib_Firstname;
			}
			set
			{
				if ((this._lib_Firstname != value))
				{
					this.Onlib_FirstnameChanging(value);
					this.SendPropertyChanging();
					this._lib_Firstname = value;
					this.SendPropertyChanged("lib_Firstname");
					this.Onlib_FirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_Lastname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string lib_Lastname
		{
			get
			{
				return this._lib_Lastname;
			}
			set
			{
				if ((this._lib_Lastname != value))
				{
					this.Onlib_LastnameChanging(value);
					this.SendPropertyChanging();
					this._lib_Lastname = value;
					this.SendPropertyChanged("lib_Lastname");
					this.Onlib_LastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_Gender", DbType="VarChar(10)")]
		public string lib_Gender
		{
			get
			{
				return this._lib_Gender;
			}
			set
			{
				if ((this._lib_Gender != value))
				{
					this.Onlib_GenderChanging(value);
					this.SendPropertyChanging();
					this._lib_Gender = value;
					this.SendPropertyChanged("lib_Gender");
					this.Onlib_GenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_Address", DbType="VarChar(100)")]
		public string lib_Address
		{
			get
			{
				return this._lib_Address;
			}
			set
			{
				if ((this._lib_Address != value))
				{
					this.Onlib_AddressChanging(value);
					this.SendPropertyChanging();
					this._lib_Address = value;
					this.SendPropertyChanged("lib_Address");
					this.Onlib_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_ContactNumber", DbType="VarChar(50)")]
		public string lib_ContactNumber
		{
			get
			{
				return this._lib_ContactNumber;
			}
			set
			{
				if ((this._lib_ContactNumber != value))
				{
					this.Onlib_ContactNumberChanging(value);
					this.SendPropertyChanging();
					this._lib_ContactNumber = value;
					this.SendPropertyChanged("lib_ContactNumber");
					this.Onlib_ContactNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_UserType", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string lib_UserType
		{
			get
			{
				return this._lib_UserType;
			}
			set
			{
				if ((this._lib_UserType != value))
				{
					this.Onlib_UserTypeChanging(value);
					this.SendPropertyChanging();
					this._lib_UserType = value;
					this.SendPropertyChanged("lib_UserType");
					this.Onlib_UserTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_SchoolYear", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string lib_SchoolYear
		{
			get
			{
				return this._lib_SchoolYear;
			}
			set
			{
				if ((this._lib_SchoolYear != value))
				{
					this.Onlib_SchoolYearChanging(value);
					this.SendPropertyChanging();
					this._lib_SchoolYear = value;
					this.SendPropertyChanged("lib_SchoolYear");
					this.Onlib_SchoolYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_WithCard", DbType="Bit")]
		public System.Nullable<bool> lib_WithCard
		{
			get
			{
				return this._lib_WithCard;
			}
			set
			{
				if ((this._lib_WithCard != value))
				{
					this.Onlib_WithCardChanging(value);
					this.SendPropertyChanging();
					this._lib_WithCard = value;
					this.SendPropertyChanged("lib_WithCard");
					this.Onlib_WithCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLibraryUser_tblBorrow", Storage="_tblBorrows", ThisKey="lib_UserID", OtherKey="lib_UserID")]
		public EntitySet<tblBorrow> tblBorrows
		{
			get
			{
				return this._tblBorrows;
			}
			set
			{
				this._tblBorrows.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblBorrows(tblBorrow entity)
		{
			this.SendPropertyChanging();
			entity.tblLibraryUser = this;
		}
		
		private void detach_tblBorrows(tblBorrow entity)
		{
			this.SendPropertyChanging();
			entity.tblLibraryUser = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSelectedBooks")]
	public partial class tblSelectedBook : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sb_BookID;
		
		private string _sb_BookIDNum;
		
		private string _sb_Title;
		
		private System.DateTime _sb_DueDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsb_BookIDChanging(int value);
    partial void Onsb_BookIDChanged();
    partial void Onsb_BookIDNumChanging(string value);
    partial void Onsb_BookIDNumChanged();
    partial void Onsb_TitleChanging(string value);
    partial void Onsb_TitleChanged();
    partial void Onsb_DueDateChanging(System.DateTime value);
    partial void Onsb_DueDateChanged();
    #endregion
		
		public tblSelectedBook()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sb_BookID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sb_BookID
		{
			get
			{
				return this._sb_BookID;
			}
			set
			{
				if ((this._sb_BookID != value))
				{
					this.Onsb_BookIDChanging(value);
					this.SendPropertyChanging();
					this._sb_BookID = value;
					this.SendPropertyChanged("sb_BookID");
					this.Onsb_BookIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sb_BookIDNum", DbType="VarChar(50)")]
		public string sb_BookIDNum
		{
			get
			{
				return this._sb_BookIDNum;
			}
			set
			{
				if ((this._sb_BookIDNum != value))
				{
					this.Onsb_BookIDNumChanging(value);
					this.SendPropertyChanging();
					this._sb_BookIDNum = value;
					this.SendPropertyChanged("sb_BookIDNum");
					this.Onsb_BookIDNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sb_Title", DbType="VarChar(100)")]
		public string sb_Title
		{
			get
			{
				return this._sb_Title;
			}
			set
			{
				if ((this._sb_Title != value))
				{
					this.Onsb_TitleChanging(value);
					this.SendPropertyChanging();
					this._sb_Title = value;
					this.SendPropertyChanged("sb_Title");
					this.Onsb_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sb_DueDate", DbType="Date NOT NULL")]
		public System.DateTime sb_DueDate
		{
			get
			{
				return this._sb_DueDate;
			}
			set
			{
				if ((this._sb_DueDate != value))
				{
					this.Onsb_DueDateChanging(value);
					this.SendPropertyChanging();
					this._sb_DueDate = value;
					this.SendPropertyChanged("sb_DueDate");
					this.Onsb_DueDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_SearchBookResult
	{
		
		private string _BookIDNumber;
		
		private string _BookType;
		
		private string _ISBN;
		
		private string _CallNumber;
		
		private string _Title;
		
		private string _Author;
		
		private string _Publisher;
		
		private int _CopyrightYear;
		
		private string _Edition;
		
		private string _Volume;
		
		private System.Nullable<int> _Pages;
		
		private string _Remarks;
		
		public sp_SearchBookResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookIDNumber", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BookIDNumber
		{
			get
			{
				return this._BookIDNumber;
			}
			set
			{
				if ((this._BookIDNumber != value))
				{
					this._BookIDNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookType", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BookType
		{
			get
			{
				return this._BookType;
			}
			set
			{
				if ((this._BookType != value))
				{
					this._BookType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISBN", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ISBN
		{
			get
			{
				return this._ISBN;
			}
			set
			{
				if ((this._ISBN != value))
				{
					this._ISBN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallNumber", DbType="VarChar(50)")]
		public string CallNumber
		{
			get
			{
				return this._CallNumber;
			}
			set
			{
				if ((this._CallNumber != value))
				{
					this._CallNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author", DbType="VarChar(50)")]
		public string Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				if ((this._Author != value))
				{
					this._Author = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Publisher", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Publisher
		{
			get
			{
				return this._Publisher;
			}
			set
			{
				if ((this._Publisher != value))
				{
					this._Publisher = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CopyrightYear", DbType="Int NOT NULL")]
		public int CopyrightYear
		{
			get
			{
				return this._CopyrightYear;
			}
			set
			{
				if ((this._CopyrightYear != value))
				{
					this._CopyrightYear = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edition", DbType="VarChar(50)")]
		public string Edition
		{
			get
			{
				return this._Edition;
			}
			set
			{
				if ((this._Edition != value))
				{
					this._Edition = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="VarChar(50)")]
		public string Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this._Volume = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pages", DbType="Int")]
		public System.Nullable<int> Pages
		{
			get
			{
				return this._Pages;
			}
			set
			{
				if ((this._Pages != value))
				{
					this._Pages = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="VarChar(200)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
	}
	
	public partial class sp_TotalBookCopyResult
	{
		
		private int _copy_AccNum;
		
		public sp_TotalBookCopyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_copy_AccNum", DbType="Int NOT NULL")]
		public int copy_AccNum
		{
			get
			{
				return this._copy_AccNum;
			}
			set
			{
				if ((this._copy_AccNum != value))
				{
					this._copy_AccNum = value;
				}
			}
		}
	}
	
	public partial class sp_ViewBookResult
	{
		
		private string _BookIDNumber;
		
		private string _BookType;
		
		private string _CallNumber;
		
		private string _Title;
		
		private string _Author;
		
		private int _CopyrightYear;
		
		public sp_ViewBookResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookIDNumber", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BookIDNumber
		{
			get
			{
				return this._BookIDNumber;
			}
			set
			{
				if ((this._BookIDNumber != value))
				{
					this._BookIDNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookType", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BookType
		{
			get
			{
				return this._BookType;
			}
			set
			{
				if ((this._BookType != value))
				{
					this._BookType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallNumber", DbType="VarChar(50)")]
		public string CallNumber
		{
			get
			{
				return this._CallNumber;
			}
			set
			{
				if ((this._CallNumber != value))
				{
					this._CallNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author", DbType="VarChar(50)")]
		public string Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				if ((this._Author != value))
				{
					this._Author = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CopyrightYear", DbType="Int NOT NULL")]
		public int CopyrightYear
		{
			get
			{
				return this._CopyrightYear;
			}
			set
			{
				if ((this._CopyrightYear != value))
				{
					this._CopyrightYear = value;
				}
			}
		}
	}
	
	public partial class sp_ViewBookCopyResult
	{
		
		private string _BookIDNumber;
		
		private int _AccessionNumber;
		
		private System.Nullable<System.DateTime> _DateReceived;
		
		private string _Status;
		
		public sp_ViewBookCopyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookIDNumber", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BookIDNumber
		{
			get
			{
				return this._BookIDNumber;
			}
			set
			{
				if ((this._BookIDNumber != value))
				{
					this._BookIDNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessionNumber", DbType="Int NOT NULL")]
		public int AccessionNumber
		{
			get
			{
				return this._AccessionNumber;
			}
			set
			{
				if ((this._AccessionNumber != value))
				{
					this._AccessionNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateReceived", DbType="Date")]
		public System.Nullable<System.DateTime> DateReceived
		{
			get
			{
				return this._DateReceived;
			}
			set
			{
				if ((this._DateReceived != value))
				{
					this._DateReceived = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class sp_ViewLibraryUserResult
	{
		
		private int _lib_UserID;
		
		private string _lib_SchoolID;
		
		private string _lib_Firstname;
		
		private string _lib_Lastname;
		
		private string _lib_Gender;
		
		private string _lib_Address;
		
		private string _lib_ContactNumber;
		
		private string _lib_UserType;
		
		private string _lib_SchoolYear;
		
		private System.Nullable<bool> _lib_WithCard;
		
		public sp_ViewLibraryUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_UserID", DbType="Int NOT NULL")]
		public int lib_UserID
		{
			get
			{
				return this._lib_UserID;
			}
			set
			{
				if ((this._lib_UserID != value))
				{
					this._lib_UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_SchoolID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string lib_SchoolID
		{
			get
			{
				return this._lib_SchoolID;
			}
			set
			{
				if ((this._lib_SchoolID != value))
				{
					this._lib_SchoolID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_Firstname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string lib_Firstname
		{
			get
			{
				return this._lib_Firstname;
			}
			set
			{
				if ((this._lib_Firstname != value))
				{
					this._lib_Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_Lastname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string lib_Lastname
		{
			get
			{
				return this._lib_Lastname;
			}
			set
			{
				if ((this._lib_Lastname != value))
				{
					this._lib_Lastname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_Gender", DbType="VarChar(10)")]
		public string lib_Gender
		{
			get
			{
				return this._lib_Gender;
			}
			set
			{
				if ((this._lib_Gender != value))
				{
					this._lib_Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_Address", DbType="VarChar(100)")]
		public string lib_Address
		{
			get
			{
				return this._lib_Address;
			}
			set
			{
				if ((this._lib_Address != value))
				{
					this._lib_Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_ContactNumber", DbType="VarChar(50)")]
		public string lib_ContactNumber
		{
			get
			{
				return this._lib_ContactNumber;
			}
			set
			{
				if ((this._lib_ContactNumber != value))
				{
					this._lib_ContactNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_UserType", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string lib_UserType
		{
			get
			{
				return this._lib_UserType;
			}
			set
			{
				if ((this._lib_UserType != value))
				{
					this._lib_UserType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_SchoolYear", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string lib_SchoolYear
		{
			get
			{
				return this._lib_SchoolYear;
			}
			set
			{
				if ((this._lib_SchoolYear != value))
				{
					this._lib_SchoolYear = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lib_WithCard", DbType="Bit")]
		public System.Nullable<bool> lib_WithCard
		{
			get
			{
				return this._lib_WithCard;
			}
			set
			{
				if ((this._lib_WithCard != value))
				{
					this._lib_WithCard = value;
				}
			}
		}
	}
	
	public partial class sp_ViewSelectedBooksResult
	{
		
		private string _BookIDNum;
		
		private string _Title;
		
		private System.DateTime _DueDate;
		
		public sp_ViewSelectedBooksResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookIDNum", DbType="VarChar(50)")]
		public string BookIDNum
		{
			get
			{
				return this._BookIDNum;
			}
			set
			{
				if ((this._BookIDNum != value))
				{
					this._BookIDNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(100)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueDate", DbType="Date NOT NULL")]
		public System.DateTime DueDate
		{
			get
			{
				return this._DueDate;
			}
			set
			{
				if ((this._DueDate != value))
				{
					this._DueDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
