<?xml version="1.0" encoding="utf-8"?><Database Name="dbLibraryManagement" Class="dcLMSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DELL-PC\SQLEXPRESS;Initial Catalog=dbLibraryManagement;Integrated Security=True" SettingsObjectName="QRCodeBasedLMS.Properties.Settings" SettingsPropertyName="dbLibraryManagementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblAttendance" Member="tblAttendances">
    <Type Name="tblAttendance">
      <Column Name="attendance_AttendanceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="attendance_StudentIDNum" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="attendance_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="attendance_LoginTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblUserAccount" Member="tblUserAccounts">
    <Type Name="tblUserAccount">
      <Column Name="user_UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_UserNum" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="user_Firstname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="user_Lastname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="user_Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="user_Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="user_SecretQuestion" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="user_SecretAnswer" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="user_UserType" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="user_Status" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblBook" Member="tblBooks">
    <Type Name="tblBook">
      <Column Name="book_BookID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="book_BookNum" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="book_BookType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="book_ISBN" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="book_CallNum" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="book_Title" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="book_Author" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="book_Publisher" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="book_CopyrightYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="book_Edition" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="book_Volume" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="book_Pages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="book_Remarks" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="tblBook_tblBookCopy" Member="tblBookCopies" ThisKey="book_BookID" OtherKey="book_BookID" Type="tblBookCopy" />
      <Association Name="tblBook_tblBorrow" Member="tblBorrows" ThisKey="book_BookID" OtherKey="book_BookID" Type="tblBorrow" />
    </Type>
  </Table>
  <Table Name="dbo.tblBookCopy" Member="tblBookCopies">
    <Type Name="tblBookCopy">
      <Column Name="copy_CopyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="copy_AccNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="copy_DateReceived" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="book_Status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="book_BookID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblBook_tblBookCopy" Member="tblBook" ThisKey="book_BookID" OtherKey="book_BookID" Type="tblBook" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblBorrow" Member="tblBorrows">
    <Type Name="tblBorrow">
      <Column Name="borrow_BorrowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="borrow_BorrowNum" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lib_UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="book_BookID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="borrow_BorrowedDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="borrow_DueDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="tblBook_tblBorrow" Member="tblBook" ThisKey="book_BookID" OtherKey="book_BookID" Type="tblBook" IsForeignKey="true" />
      <Association Name="tblLibraryUser_tblBorrow" Member="tblLibraryUser" ThisKey="lib_UserID" OtherKey="lib_UserID" Type="tblLibraryUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblLibraryUser" Member="tblLibraryUsers">
    <Type Name="tblLibraryUser">
      <Column Name="lib_UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lib_SchoolID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="lib_Firstname" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="lib_Lastname" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="lib_Gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="lib_Address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="lib_ContactNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lib_UserType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lib_SchoolYear" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lib_WithCard" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblLibraryUser_tblBorrow" Member="tblBorrows" ThisKey="lib_UserID" OtherKey="lib_UserID" Type="tblBorrow" />
    </Type>
  </Table>
  <Table Name="dbo.tblSelectedBooks" Member="tblSelectedBooks">
    <Type Name="tblSelectedBook">
      <Column Name="sb_BookID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sb_BookIDNum" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="sb_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="sb_DueDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.sp_AccountIDnumber" Method="sp_AccountIDnumber">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_AddAccount" Method="sp_AddAccount" IsComposable="true">
    <Parameter Name="UserNum" Parameter="userNum" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Firstname" Parameter="firstname" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Lastname" Parameter="lastname" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SecretQuestion" Parameter="secretQuestion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="SecretAnswer" Parameter="secretAnswer" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="UserType" Parameter="userType" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(10)" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.sp_AddBook" Method="sp_AddBook">
    <Parameter Name="BookNum" Parameter="bookNum" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="BookType" Parameter="bookType" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ISBN" Parameter="iSBN" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="AccNum" Parameter="accNum" Type="System.Int32" DbType="Int" />
    <Parameter Name="CallNum" Parameter="callNum" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="DateReceived" Parameter="dateReceived" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Author" Parameter="author" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Publisher" Parameter="publisher" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CopyrightYear" Parameter="copyrightYear" Type="System.Int32" DbType="Int" />
    <Parameter Name="Edition" Parameter="edition" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Volume" Parameter="volume" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Pages" Parameter="pages" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Remarks" Parameter="remarks" Type="System.String" DbType="VarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_AddBookCopy" Method="sp_AddBookCopy">
    <Parameter Name="BookNum" Parameter="bookNum" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="AccNum" Parameter="accNum" Type="System.Int32" DbType="Int" />
    <Parameter Name="DateReceived" Parameter="dateReceived" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_AddBorrower" Method="sp_AddBorrower" IsComposable="true">
    <Parameter Name="BorrowerNum" Parameter="borrowerNum" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Firstname" Parameter="firstname" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Lastname" Parameter="lastname" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Section" Parameter="section" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ContactNumber" Parameter="contactNumber" Type="System.String" DbType="VarChar(50)" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.sp_AddLibraryUser" Method="sp_AddLibraryUser">
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Firstname" Parameter="firstname" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Lastname" Parameter="lastname" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ContactNumber" Parameter="contactNumber" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="UserType" Parameter="userType" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SchoolYear" Parameter="schoolYear" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="WithLibraryCard" Parameter="withLibraryCard" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Attendance" Method="sp_Attendance">
    <Parameter Name="StudentID" Parameter="studentID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LoginTime" Parameter="loginTime" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BookIDnumber" Method="sp_BookIDnumber">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BorrowIDnumber" Method="sp_BorrowIDnumber">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_SearchActiveAccount" Method="sp_SearchActiveAccount" IsComposable="true">
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="searchkey" Type="System.String" DbType="VarChar(50)" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.sp_SearchBook" Method="sp_SearchBook">
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="searchKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_SearchBookResult">
      <Column Name="BookIDNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BookType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ISBN" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CallNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Publisher" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CopyrightYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Edition" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Volume" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SearchBorrower" Method="sp_SearchBorrower" IsComposable="true">
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="searchkey" Type="System.String" DbType="VarChar(50)" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.sp_SearchInactiveAccount" Method="sp_SearchInactiveAccount" IsComposable="true">
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="searchkey" Type="System.String" DbType="VarChar(50)" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.sp_TotalBookCopy" Method="sp_TotalBookCopy">
    <Parameter Name="BookNum" Parameter="bookNum" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_TotalBookCopyResult">
      <Column Name="copy_AccNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UpdateAccount" Method="sp_UpdateAccount" IsComposable="true">
    <Parameter Name="UserNum" Parameter="userNum" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Firstname" Parameter="firstname" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Lastname" Parameter="lastname" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SecretQuestion" Parameter="secretQuestion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="SecretAnswer" Parameter="secretAnswer" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="UserType" Parameter="userType" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(10)" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.sp_UpdateAccountStatus" Method="sp_UpdateAccountStatus" IsComposable="true">
    <Parameter Name="UserNum" Parameter="userNum" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(10)" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.sp_UpdateBook" Method="sp_UpdateBook">
    <Parameter Name="BookNum" Parameter="bookNum" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="BookType" Parameter="bookType" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ISBN" Parameter="iSBN" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CallNum" Parameter="callNum" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Author" Parameter="author" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Publisher" Parameter="publisher" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CopyrightYear" Parameter="copyrightYear" Type="System.Int32" DbType="Int" />
    <Parameter Name="Edition" Parameter="edition" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Volume" Parameter="volume" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Pages" Parameter="pages" Type="System.Int32" DbType="Int" />
    <Parameter Name="Remarks" Parameter="remarks" Type="System.String" DbType="VarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UpdateBorrower" Method="sp_UpdateBorrower" IsComposable="true">
    <Parameter Name="BorrowerNum" Parameter="borrowerNum" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Firstname" Parameter="firstname" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Lastname" Parameter="lastname" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Section" Parameter="section" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ContactNumber" Parameter="contactNumber" Type="System.String" DbType="VarChar(50)" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.sp_UpdateLibraryUser" Method="sp_UpdateLibraryUser">
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Firstname" Parameter="firstname" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Lastname" Parameter="lastname" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ContactNumber" Parameter="contactNumber" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SchoolYear" Parameter="schoolYear" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="WithLibraryCard" Parameter="withLibraryCard" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ViewActiveAccount" Method="sp_ViewActiveAccount" IsComposable="true">
    <Return Type="object" />
  </Function>
  <Function Name="dbo.sp_ViewBook" Method="sp_ViewBook">
    <ElementType Name="sp_ViewBookResult">
      <Column Name="BookIDNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BookType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CallNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CopyrightYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewBookCopy" Method="sp_ViewBookCopy">
    <Parameter Name="BookNum" Parameter="bookNum" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_ViewBookCopyResult">
      <Column Name="BookIDNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AccessionNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateReceived" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewBorrower" Method="sp_ViewBorrower" IsComposable="true">
    <Return Type="object" />
  </Function>
  <Function Name="dbo.sp_ViewInactiveAccount" Method="sp_ViewInactiveAccount" IsComposable="true">
    <Return Type="object" />
  </Function>
  <Function Name="dbo.sp_ViewLibraryUser" Method="sp_ViewLibraryUser">
    <Parameter Name="SchoolYear" Parameter="schoolYear" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_ViewLibraryUserResult">
      <Column Name="lib_UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lib_SchoolID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="lib_Firstname" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="lib_Lastname" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="lib_Gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="lib_Address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="lib_ContactNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lib_UserType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lib_SchoolYear" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lib_WithCard" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_DeleteSelectedBooks" Method="sp_DeleteSelectedBooks">
    <Parameter Name="BookIDNum" Parameter="bookIDNum" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ViewSelectedBooks" Method="sp_ViewSelectedBooks">
    <ElementType Name="sp_ViewSelectedBooksResult">
      <Column Name="BookIDNum" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DueDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_BorrowBook" Method="sp_BorrowBook">
    <Parameter Name="BorrowNum" Parameter="borrowNum" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="BookNum" Parameter="bookNum" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="BorrowedDate" Parameter="borrowedDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DueDate" Parameter="dueDate" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_SelectBooks" Method="sp_SelectBooks">
    <Parameter Name="BookNum" Parameter="bookNum" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DueDate" Parameter="dueDate" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
</Database>